# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='version',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
